/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\Repositories\\Notes\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-211d55ee",
    path: "/Java/IO/IO.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-211d55ee").then(next)
    },
  },
  {
    name: "v-30273973",
    path: "/Java/%E5%B8%B8%E7%94%A8API/%E5%B8%B8%E7%94%A8API.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-30273973").then(next)
    },
  },
  {
    path: "/Java/常用API/常用API.html",
    redirect: "/Java/%E5%B8%B8%E7%94%A8API/%E5%B8%B8%E7%94%A8API.html"
  },
  {
    path: "/Java/常用API/常用API.html",
    redirect: "/Java/%E5%B8%B8%E7%94%A8API/%E5%B8%B8%E7%94%A8API.html"
  },
  {
    name: "v-386ba049",
    path: "/Java/Java%E5%9F%BA%E7%A1%80/Java%E5%9F%BA%E7%A1%80.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-386ba049").then(next)
    },
  },
  {
    path: "/Java/Java基础/Java基础.html",
    redirect: "/Java/Java%E5%9F%BA%E7%A1%80/Java%E5%9F%BA%E7%A1%80.html"
  },
  {
    path: "/Java/Java基础/Java基础.html",
    redirect: "/Java/Java%E5%9F%BA%E7%A1%80/Java%E5%9F%BA%E7%A1%80.html"
  },
  {
    name: "v-360960ae",
    path: "/Java/Java%E5%9F%BA%E7%A1%80%E8%AF%AD%E6%B3%95/Java%E5%9F%BA%E7%A1%80%E8%AF%AD%E6%B3%95.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-360960ae").then(next)
    },
  },
  {
    path: "/Java/Java基础语法/Java基础语法.html",
    redirect: "/Java/Java%E5%9F%BA%E7%A1%80%E8%AF%AD%E6%B3%95/Java%E5%9F%BA%E7%A1%80%E8%AF%AD%E6%B3%95.html"
  },
  {
    path: "/Java/Java基础语法/Java基础语法.html",
    redirect: "/Java/Java%E5%9F%BA%E7%A1%80%E8%AF%AD%E6%B3%95/Java%E5%9F%BA%E7%A1%80%E8%AF%AD%E6%B3%95.html"
  },
  {
    name: "v-b5dfee7a",
    path: "/Java/%E5%A4%9A%E7%BA%BF%E7%A8%8B/%E5%A4%9A%E7%BA%BF%E7%A8%8B.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b5dfee7a").then(next)
    },
  },
  {
    path: "/Java/多线程/多线程.html",
    redirect: "/Java/%E5%A4%9A%E7%BA%BF%E7%A8%8B/%E5%A4%9A%E7%BA%BF%E7%A8%8B.html"
  },
  {
    path: "/Java/多线程/多线程.html",
    redirect: "/Java/%E5%A4%9A%E7%BA%BF%E7%A8%8B/%E5%A4%9A%E7%BA%BF%E7%A8%8B.html"
  },
  {
    name: "v-128749e9",
    path: "/Java/%E7%BD%91%E7%BB%9C%E7%BC%96%E7%A8%8B/%E7%BD%91%E7%BB%9C%E7%BC%96%E7%A8%8B.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-128749e9").then(next)
    },
  },
  {
    path: "/Java/网络编程/网络编程.html",
    redirect: "/Java/%E7%BD%91%E7%BB%9C%E7%BC%96%E7%A8%8B/%E7%BD%91%E7%BB%9C%E7%BC%96%E7%A8%8B.html"
  },
  {
    path: "/Java/网络编程/网络编程.html",
    redirect: "/Java/%E7%BD%91%E7%BB%9C%E7%BC%96%E7%A8%8B/%E7%BD%91%E7%BB%9C%E7%BC%96%E7%A8%8B.html"
  },
  {
    name: "v-2d297d7e",
    path: "/Java/%E6%95%B0%E6%8D%AE%E5%BA%93/%E6%95%B0%E6%8D%AE%E5%BA%93.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2d297d7e").then(next)
    },
  },
  {
    path: "/Java/数据库/数据库.html",
    redirect: "/Java/%E6%95%B0%E6%8D%AE%E5%BA%93/%E6%95%B0%E6%8D%AE%E5%BA%93.html"
  },
  {
    path: "/Java/数据库/数据库.html",
    redirect: "/Java/%E6%95%B0%E6%8D%AE%E5%BA%93/%E6%95%B0%E6%8D%AE%E5%BA%93.html"
  },
  {
    name: "v-75e26aa9",
    path: "/Java/%E5%BC%82%E5%B8%B8/%E5%BC%82%E5%B8%B8.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-75e26aa9").then(next)
    },
  },
  {
    path: "/Java/异常/异常.html",
    redirect: "/Java/%E5%BC%82%E5%B8%B8/%E5%BC%82%E5%B8%B8.html"
  },
  {
    path: "/Java/异常/异常.html",
    redirect: "/Java/%E5%BC%82%E5%B8%B8/%E5%BC%82%E5%B8%B8.html"
  },
  {
    name: "v-486a6a6e",
    path: "/Java/Java%E9%9D%A2%E5%90%91%E5%AF%B9%E8%B1%A1/Java%E9%9D%A2%E5%90%91%E5%AF%B9%E8%B1%A1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-486a6a6e").then(next)
    },
  },
  {
    path: "/Java/Java面向对象/Java面向对象.html",
    redirect: "/Java/Java%E9%9D%A2%E5%90%91%E5%AF%B9%E8%B1%A1/Java%E9%9D%A2%E5%90%91%E5%AF%B9%E8%B1%A1.html"
  },
  {
    path: "/Java/Java面向对象/Java面向对象.html",
    redirect: "/Java/Java%E9%9D%A2%E5%90%91%E5%AF%B9%E8%B1%A1/Java%E9%9D%A2%E5%90%91%E5%AF%B9%E8%B1%A1.html"
  },
  {
    name: "v-aa2f5e2e",
    path: "/Java/%E7%B1%BB%E5%8A%A0%E8%BD%BD%E3%80%81%E5%8F%8D%E5%B0%84/%E7%B1%BB%E5%8A%A0%E8%BD%BD%E3%80%81%E5%8F%8D%E5%B0%84.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-aa2f5e2e").then(next)
    },
  },
  {
    path: "/Java/类加载、反射/类加载、反射.html",
    redirect: "/Java/%E7%B1%BB%E5%8A%A0%E8%BD%BD%E3%80%81%E5%8F%8D%E5%B0%84/%E7%B1%BB%E5%8A%A0%E8%BD%BD%E3%80%81%E5%8F%8D%E5%B0%84.html"
  },
  {
    path: "/Java/类加载、反射/类加载、反射.html",
    redirect: "/Java/%E7%B1%BB%E5%8A%A0%E8%BD%BD%E3%80%81%E5%8F%8D%E5%B0%84/%E7%B1%BB%E5%8A%A0%E8%BD%BD%E3%80%81%E5%8F%8D%E5%B0%84.html"
  },
  {
    name: "v-1f3144e9",
    path: "/Java/%E9%A1%B9%E7%9B%AE/%E9%A1%B9%E7%9B%AE.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1f3144e9").then(next)
    },
  },
  {
    path: "/Java/项目/项目.html",
    redirect: "/Java/%E9%A1%B9%E7%9B%AE/%E9%A1%B9%E7%9B%AE.html"
  },
  {
    path: "/Java/项目/项目.html",
    redirect: "/Java/%E9%A1%B9%E7%9B%AE/%E9%A1%B9%E7%9B%AE.html"
  },
  {
    name: "v-e4726c4c",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e4726c4c").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-70a0c66e",
    path: "/Java/%E9%9B%86%E5%90%88/%E9%9B%86%E5%90%88.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-70a0c66e").then(next)
    },
  },
  {
    path: "/Java/集合/集合.html",
    redirect: "/Java/%E9%9B%86%E5%90%88/%E9%9B%86%E5%90%88.html"
  },
  {
    path: "/Java/集合/集合.html",
    redirect: "/Java/%E9%9B%86%E5%90%88/%E9%9B%86%E5%90%88.html"
  },
  {
    name: "v-3d8a75e0",
    path: "/MySQL/MySQL%E5%9F%BA%E7%A1%80%E7%AF%87.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3d8a75e0").then(next)
    },
  },
  {
    path: "/MySQL/MySQL基础篇.html",
    redirect: "/MySQL/MySQL%E5%9F%BA%E7%A1%80%E7%AF%87.html"
  },
  {
    path: "/MySQL/MySQL基础篇.html",
    redirect: "/MySQL/MySQL%E5%9F%BA%E7%A1%80%E7%AF%87.html"
  },
  {
    name: "v-92fc7c3e",
    path: "/about.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-92fc7c3e").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]